# Generated by Django 6.1 on 2026-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_district_county_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ('order', 'id'), 'verbose_name': 'تصویر ملک', 'verbose_name_plural': 'تصاویر ملک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان/ایالت', 'verbose_name_plural': 'استان ها / ایالت ها'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='کد کشور'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='نام کشور'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شهرستان'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='address',
            field=models.CharField(blank=True, default=1, max_length=350, verbose_name='آدرس تکمیلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='ruraldistrict',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام دهستان'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.UniqueConstraint(fields=('province', 'code'), name='unique_county_code_per_province'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('property_obj',), name='unique_cover_per_property'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('country', 'code'), name='unique_province_code_per_country'),
        ),
    ]
