# Generated by Django 6.1 on 2026-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_propertyimage_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyrule',
            options={'verbose_name': 'قانون ملک', 'verbose_name_plural': 'قوانین ملک'},
        ),
        migrations.AddConstraint(
            model_name='propertyrule',
            constraint=models.UniqueConstraint(condition=models.Q(('amenity__isnull', False)), fields=('property_obj', 'rule_key', 'amenity'), name='unique_rule_per_property_amenity'),
        ),
        migrations.AddConstraint(
            model_name='propertyrule',
            constraint=models.UniqueConstraint(condition=models.Q(('amenity__isnull', True)), fields=('property_obj', 'rule_key'), name='unique_general_rule_per_property'),
        ),
    ]
