# Generated by Django 6.1 on 2026-10-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertyrule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrule',
            options={'verbose_name': 'مجوز قانون', 'verbose_name_plural': 'مجوز قوانین'},
        ),
        migrations.AlterModelOptions(
            name='quantityrule',
            options={'verbose_name': 'مجوز قانون', 'verbose_name_plural': 'مجوز قوانین'},
        ),
        migrations.AlterModelOptions(
            name='timerule',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
